const progress=document.getElementById('scrollProgress');const nav=document.getElementById('nav');
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${(scrollY/h)*100}%`;nav.classList.toggle('scrolled',scrollY>20)});
const observer=new IntersectionObserver((entries)=>entries.forEach((e,i)=>{if(e.isIntersecting){setTimeout(()=>e.target.classList.add('visible'),i*55);observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const fine=matchMedia('(pointer:fine)').matches;
if(!reduced&&fine){document.querySelectorAll('.tilt').forEach(card=>{const max=Number(card.dataset.tilt||6);card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateX(${-y*max}deg) rotateY(${x*max}deg) translateZ(0)`});card.addEventListener('mouseleave',()=>card.style.transform='')})}
const modal=document.getElementById('configModal'),openBuilder=document.getElementById('openBuilder'),closeBuilder=document.getElementById('closeBuilder'),pcForm=document.getElementById('pcForm');
if(openBuilder&&modal){openBuilder.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')})}
if(closeBuilder&&modal){closeBuilder.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')})}
if(modal){modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}})}
if(pcForm){pcForm.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(pcForm);const msg=`Olá! Fiz o configurador no site da Game Over Games.%0A%0AOrçamento: ${encodeURIComponent(d.get('orcamento'))}%0AJogos: ${encodeURIComponent(d.get('jogos'))}%0APeriféricos: ${encodeURIComponent(d.get('perifericos'))}%0APrioridade: ${encodeURIComponent(d.get('prioridade'))}%0AStreaming: ${encodeURIComponent(d.get('streaming'))}%0APagamento: ${encodeURIComponent(d.get('pagamento'))}%0A%0AGostaria de receber uma configuração recomendada.`;window.open(`https://wa.me/554796253895?text=${msg}`,'_blank')})}
const floating=document.getElementById('floatingContact');if(floating){const sections=[['pc','Montar meu PC','Olá! Quero montar um PC gamer.'],['servicos','Solicitar avaliação','Olá! Quero solicitar uma avaliação técnica.'],['estoque','Ver disponibilidade','Olá! Quero consultar os produtos disponíveis nesta semana.']];const ctxObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const found=sections.find(s=>s[0]===e.target.id);if(found){floating.querySelector('span').textContent=found[1];floating.href=`https://wa.me/554796253895?text=${encodeURIComponent(found[2])}`}}}),{threshold:.42});sections.forEach(s=>{const el=document.getElementById(s[0]);if(el)ctxObs.observe(el)})}
